#!/bin/bash

#SHARED_DIR="/home/islandora/setup"
DOWNLOAD_DIR="/home/islandora/setup/downloads"
FITS_VERSION=1.0.6
SOLR_VERSION=4.2.0

# fedora db creation 
MYSQL_USER=""
MYSQL_PASS=""
FEDORA_DBUSER=""
FEDORA_DBPASS=""
MYSQLROOT=""
#drupal db creation
ADMINPASS=""
